### ISSUE TITLE
fzf Alt-c moving not working

### ISSUE THREAD

**Issue by steakhutzeee** [fresh2dev/zellij-autolock#1]
Hi,

thank you for this plugin!

I'm experiencing an issue with `fzf`. It works fine with the `fzf` command. But with `fzf's Alt+c` I'm not able to use` Ctrl-j/k` to move up and down.

No issue with `zoxide's zi command` for example.

You think this could be fixed?

EDIT: I think this happens because I'm using also https://github.com/hiasr/vim-zellij-navigator
Proof is that this issue is absent if I launch `Alt+c` when I'm already in locked mode (so out of scope of the plugin above)

So I do not understand why if I launch directly the `fzf` command, then `Ctrl-j/k` work fine.

I tried to disable `vim-zellij-navigator` so using only [zellij.vim](https://github.com/fresh2dev/zellij.vim) but that way I'm able to move OUT of nvim but I'm not able to move IN nvim from a Zellij pane.

**Comment by fresh2dev** [comment]
You were good in disabling the vim-zellij-navigator plugin; I imagine it would conflict with this. Seamless Zellij/Vim nav is possible using only zellij-autolock and zellj.vim, but you also need to configure the movements in your Zellij config. Here's mine:

https://github.com/fresh2dev/dotfiles/blob/main/home/.config/zellij/config.kdl

**Comment by steakhutzeee** [comment]
Thanks, applied config similar to yours, navigation seems ok, but issue with `fzf Alt+c` persists.

No issue with `zi` .

Noted that `Alt+c` does not lock Zellij.

Suppose that the issue is there, and Zellij has the movement keys binded in `shared_except "locked"`. So Alt+c runs in Normal and when I use Ctrl-j/k Zellij just tries to move to another pane.

**Comment by fresh2dev** [comment]
Ah, I see what you mean now. I don't use these specific FZF keybindings, but I ran into a similar issue with Ctrl+R for my shell history menu. 

The solution is to activate the zellij-unlock plugin with these specific mappings within your Zellij config. 

https://github.com/fresh2dev/dotfiles/blob/106b36b05d89e1ea6f2eab392cfb845d44e41536/home/.config/zellij/config.kdl#L78

Notice how I bind enter, passthru enter, then activate the autolock plugin. 

I do the same thing for Ctrl+R (my shell history menu). Here is where you'll want to define additional mappings (Ctrl+t, Alt+c). You'll want to be sure the call to "WriteChars" passes the appropriate ASCII code for the respective key you want to intercept/passthru.

**Comment by fresh2dev** [comment]
This plugin reacts to events like "PaneUpdate" to examine the running process and determine if Zellij should lock. 

When you invoke a command *in the existing pane*, no event is fired. For this plugin to work in this case, you must bind/intercept/relay the `Enter` key, so `$ fzf<enter>` will trigger this plugin. The same logic applies for other keys that invoke a `trigger` program, like Ctrl+R, Ctrl+T, etc.

**Comment by steakhutzeee** [comment]
Thank you! Set `Ctrl-t` correctly.

I'm trying to figure out if it's possible to map `Alt-c` now. Any hint?

**Comment by fresh2dev** [comment]
I'm not sure. I use zoxide's `zi` command for switching dirs. Until a solution is found, I'd consider this a limitation of this plugin (the inability to passthru the `Alt` key). I personally dedicate `Alt` for the Zellij-layer, so I've not encountered this.

**Comment by steakhutzeee** [comment]
Not a big deal actually. I think this issue can be closed if you want :)

Thank you for your support!

**Comment by fresh2dev** [comment]
> the screen flashes continuously

I've seen some minor flashing in the tab-bar when rapidly changing tabs in Vim (because I use a Vim autocmd to name the Zellij tab after Vim's working directory), but nothing really bothersome. If you continue to have this issue, I'd ask that you open a new Github issue with a link to your Zellij config and maybe a GIF/demo so I can see what you're experiencing.
