### ISSUE TITLE
Detected command in pane is absolute path

### ISSUE THREAD

**Issue by ADIX7** [fresh2dev/zellij-autolock#10]
`zellij --version`: 0.41.2

Terminal version: Latest stable wezterm with latest nushell

Operating system: Fedora Linux

## Issue description

At first glance the plugine seemed to not work but after inspecting the logs I found these:
```
Detected command in pane: /usr/bin/nvim
Detected command in pane: /usr/local/bin/atuin history start -- nvim
```

So it looks like full path with arguments are detected and because of this no locking happened.

## Minimal reproduction

I'm not sure if it is me, so I don't know the exact circumstances, I simple followed the README. When using the absolute path of nvim the locking works.

**Comment by fresh2dev** [comment]
Interesting; thanks for sharing. I suspect it has to do with the use of Wezterm. I use Alacritty.

This isn't necessarily a bug with this plugin, but I will update the docs to mention for this if we can isolate the cause.

Could you try with Alacritty or some other terminal and let us know what the logs say?

**Comment by ADIX7** [comment]
Sorry for the late answer. I tested with gnome terminal and it works the same.

I was thinking where you get the running_command, in addition to splitting at whitespaces, you could also split at / (more specifically at os dependent directory separator, I guess) and get the last one. If only the executable name is reported it should work just as now, but with that implementation it should work when an absolute path is reported.

**Comment by fresh2dev** [comment]
I attempted a fix, but I can't test it. Try with this pre-release and LMK 🤙 

https://github.com/fresh2dev/zellij-autolock/releases/tag/0.2.2.rc1

**Comment by fresh2dev** [comment]
Removing the 'bug' label since this is most likely a config issue.

**Comment by ADIX7** [comment]
It is working now! I got the lock with atuin as well although I have not changed the config to use the full path of atuin ever, so 100%! It is a little bit confusing that the runnig_command is printed before the trimming. Maybe you could print the original command and the transformed one as well in a combined print statement.
