### ISSUE TITLE
Add move_focus_or_tab to automatically move to next tab

### ISSUE THREAD

**Issue by steakhutzeee** [fresh2dev/zellij-autolock#6]
Hi, when moving between Zellij panes/[Neo]vim windows, the controls:

`MoveFocus "Left"` and `MoveFocus "Right"` do not allow to automatically move to next Zellij tab if one is present.

Could such feature be added? This is present as `move_focus_or_tab` in https://github.com/hiasr/vim-zellij-navigator?tab=readme-ov-file#usage ([but with an issue when Neovim is running alone in a Zellij pane](https://github.com/hiasr/vim-zellij-navigator/issues/12))

Would be great if this could be added. Thank you!

**Comment by fresh2dev** [comment]
To use Zellij's move-focus-or-tab action, you would replace calls to `MoveFocus` with `MoveFocusOrTab`, e.g.:

```
shared_except "locked" {
    bind "Ctrl h" { MoveFocusOrTab "Left"; }
    bind "Ctrl l" { MoveFocusOrTab "Right"; }
    bind "Ctrl j" { MoveFocusOrTab "Down"; }
    bind "Ctrl k" { MoveFocusOrTab "Up"; }

    //...
}
```

Separately, in the [Neo]vim companion plugin [zellij.vim](https://github.com/fresh2dev/zellij.vim) v0.2.0+, set `let g:zelli_navigator_move_focus_or_tab = 1`.

**Comment by steakhutzeee** [comment]
Do I also need to use the bang ! in zellij.vim configuration?

nnoremap <silent> <C-h> :ZellijNavigateLeft!<CR>
nnoremap <silent> <C-j> :ZellijNavigateDown!<CR>
nnoremap <silent> <C-k> :ZellijNavigateUp!<CR>
nnoremap <silent> <C-l> :ZellijNavigateRight!<CR>

**Comment by fresh2dev** [comment]
You only need to define those mappings if you explicitly disable the default mappings.

**Comment by steakhutzeee** [comment]
If let g:zelli_navigator_move_focus_or_tab = 1 is specified, the defaults include a bang (!).

With the bang present, this plugin calls executes the Zellij action [move-focus-or-tab](https://zellij.dev/documentation/cli-actions#move-focus-or-tab) instead of the default action [move-focus](https://zellij.dev/documentation/cli-actions#move-focus).

Am I misreading this?

**Comment by fresh2dev** [comment]
Yeah.

> If let g:zelli_navigator_move_focus_or_tab = 1 is specified, the defaults include a bang (!).

What follows is the default mappings with the bang included.

I'll try to find time to eliminate any ambiguity in the docs.

**Comment by steakhutzeee** [comment]
Not want to be repetitive, just want to be sure I understood. If using default mappings or let g:zelli_navigator_move_focus_or_tab = 1 it's totally useless to add the mappings at all to my config. Correct? They are in the docs just for demonstration and adding them again is just reduntant.

**Comment by fresh2dev** [comment]
Exactly 👍

**Comment by fresh2dev** [comment]
I updated the README of [zellij.vim](https://github.com/fresh2dev/zellij.vim). Hope it clears things up for the next user.
