### ISSUE TITLE
Don't lock back when I click Ctrl + g

### ISSUE THREAD

**Issue by KamilKleina** [fresh2dev/zellij-autolock#9]
Update the behavior of Zellij's ctrl + g lock functionality to prevent the plugin from immediately re-locking after unlocking. Currently, when ctrl + g is pressed, the lock is briefly disabled, but the plugin automatically reactivates it right away. This change would make unlocking a manual action, giving users full control to decide when to re-enable the lock.

Expected Behavior:

 1.  Pressing ctrl + g unlocks the session and leaves it unlocked.
 2.  Lock mode remains disabled until the user presses ctrl + g again to re-enable it.

Rationale:
This adjustment gives users more flexibility and avoids frustration caused by the immediate re-locking behavior. It allows for better customization of workflows, especially for tasks requiring temporary disabling of lock mode.

**Comment by wwwdata** [comment]
Yeah version 0.2.0 is also unusable for me because of this behavior... The version before that works just fine in the latest Zellij 0.41.2 and correctly switches in/out of lock mode when I switch panes and does not override my manual choice to lock/unlock

**Comment by fresh2dev** [comment]
I whipped up some code to enable deactivating / toggling the autolock behavior via Zellij pipes. I'll do some testing and try to get it published this weekend.

This is a perfectly reasonable request, but I'm curious about why it's necessary. I never need to manually toggle the lock. Could you give me an example flow that requires manually toggling the Zellij lock?

**Comment by wwwdata** [comment]
For example to just unlock and access all features while in the vim pane like increasing split size and so on.

**Comment by KamilKleina** [comment]
Like people above said:
while I am in neovim, i want to be able to press Ctrl + G then for eample Alt + n for new pane or resize 2 neovim panes etc.

**Comment by fresh2dev** [comment]
I just published v0.2.1 which includes the ability to enable / disable autolock using Zellij message pipes:

- `MessagePlugin "autolock" {payload "disable"};` \<- disable autolock
- `MessagePlugin "autolock" {payload "enable"};` \<- enable autolock
- `MessagePlugin "autolock" {payload "toggle"};` \<- toggle autolock

You can put this before a call to `SwitchToMode` to disable autolock before switching modes, like so:

```
bind "Alt z" {
    // Disable the autolock plugin.
    MessagePlugin "autolock" {payload "disable";};
    // Unlock Zellij.
    SwitchToMode "Normal";
}
```

You can also disable autolock on launch by setting the `is_enabled` option when defining the plugin:

```
plugins {
    autolock location="file:~/.config/zellij/plugins/zellij-autolock.wasm" {
        // Enabled at start?
        is_enabled true
        // ...
    }
    // ...
}
```

See more in the updated [README](https://github.com/fresh2dev/zellij-autolock/commit/7bace33d4c4f585ef1551d46a6a86961754e9cd0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

**Comment by KamilKleina** [comment]
bind "Alt z" {
    // Disable the autolock plugin.
    MessagePlugin "autolock" {payload "disable";};
    // Unlock Zellij.
    SwitchToMode "Normal";
}


can i somehow bind that to `Ctrl + g` so it just disables itself when in neovim and unlocks zellij? and then when i press ctrl +g again OR change pane it turns itself again?

**Comment by tombruijn** [comment]
I'm trying to understand how to make this plugin work and this issue seem to be the most related. I feel I have to add the keybindings to disable auto lock to use the shell normally with the default zellij config. For example: I open zellij with the autolock plugin enabled, and it opens in normal mode, I type in `vim`, but only `vi` is entered in the command prompt because pressing `m` open the "move" menu.
Pressing `ctrl + g` to lock doesn't give me enough time to press `vim` fully unless I increase the `reaction_seconds` value or I have to press `ctrl + g` to lock every time I use a key that is also used in the normal mode mapping.
From [your dotfiles](https://github.com/fresh2dev/dotfiles/blob/827e456ec840d7e5075bbaa71658731c962c9f40/home/.config/zellij/config.kdl#L131) I get the impression I should instead remap the default normal mode mode switching keys to use modifier keys to make this work and not accidentally switch modes.
So what's the recommend config for normal mode while using this plugin?

**Comment by KamilKleina** [comment]
@fresh2dev Hey man,
thank you for your help in general.
2 things, I think something is broken right now with the plugin, it doesn't matter right now if it's vim or not, it auto locks pane. Also I am trying to achive simple thing: While I am in vim, I want be able to press Ctrl+g to unlock/lock zellij without autlock interapting my acction, and I think I am too stupid to achive that. So I want a behaviour like it:
```
1. I am in terminal - autolock doesn't do anything since it's not neovim
2. I open neovim - autlock does lock zellij since it's neovim
3. I click ctrl + g - zellij does unlocks and autolock does nothing
4. I press ctrl + g - zellij is locked again
```

**Comment by fresh2dev** [comment]
@tombruijn, I have not evaluated Zellij's new "non-colliding" preset feature, but it seems to be an alternative approach to solving the colliding keybinding problem. It looks like you'd want to either it or this autolock plugin, not both.

@KamilKleina, the behavior you're describing is correct. If that's not what you're observing, something is wrong.

To be clear, though, in step 4, Zellij will lock again, and *autolock will continue to do nothing*. If you take control manually over the locking mechanism, autolock will not re-engage until you enable it (with `MessagePlugin "autolock" {payload "enable";};`)

I pushed my most recent dotfiles. I personally use `Alt+z` to manually toggle the lock, but you can use `Ctrl+g`.

https://github.com/fresh2dev/dotfiles/blob/main/home/.config/zellij/config.kdl

Hope this helps.

**Comment by KamilKleina** [comment]
@fresh2dev Thank sir, I missed that you have 2 times disable on alt+z and for my usecase I need to enable that while it's not locked!

YOU THE BEST
